### ISSUE TITLE
Sambamba mpileup does not finish 

### ISSUE THREAD

**Issue by rernst** [lomereiter/sambamba#143] opened 2015-06-05 07:58 UTC
Hi Artem,

When using sambamba without a bed file it crashes after a while with a 'Segmentation fault' or it does not finish at all (let it run overnight and output file did not get touched).

```bash
sambamba_v0.5.4 mpileup -t 2 -o sambamba/test_full.pileup test.bam --samtools "-q 1 -f genome.fasta"
```

Samtools verions in path:
```bash
samtools --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
```

**Comment by rernst** [comment] 2015-06-12 10:41
Hi Artem, do you have any update on the status of this issue?

**Comment by lomereiter** [comment] 2015-06-12 10:57
Hi, I'm installing samtools 1.2 right now, couldn't reproduce with 1.1

**Comment by rernst** [comment] 2015-06-12 11:29
Mm, strange. Let me know if you need more information.

**Comment by jgbradley1** [comment] 2015-06-19 06:27
I just wanted to chime in for a minute and report that I was able to run mpileup with no issues. I used different samtools parameters. I've been following sambamba for awhile mainly for the mpileup feature. I'm using the same software version as well
```
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
```
Also, I am using sambamba v0.5.4 (the linux binary).
```
time sambamba mpileup -t 32 -o sambamba.mpileup.bcf.gz input.bam --samtools "-g -f genome.fa"
real    17m29.780s
user    434m58.644s
sys     10m58.520s
```
The final compressed output (sambamba.mpileup.bcf.gz) was 11GB.

**Comment by lomereiter** [comment] 2015-06-19 06:33
Hi Joshua, 
Yesterday I asked Robert in a private email for the input data and was able to reproduce the issue on my laptop. So it's indeed a bug, although a rare one.

**Comment by lomereiter** [comment] 2015-06-28 16:52
I'm investigating the issue. The segfault was because of attempt to access element of an array with -1 index (fixed in https://github.com/biod/BioD/commit/0e924443aa9895f595d36a74ecd555b4b795327d), and the deadlock apparently has to do with pipe buffering, since it seems to occur when a chunk piped to samtools is less than 65KB in size...

**Closed** 2015-06-28 19:37 UTC

**Comment by lomereiter** [comment] 2015-06-28 19:39
I made it so that the reader (samtools) always opens the FIFO before the writer, that seems to fix the issue.

**Comment by rernst** [comment] 2015-06-29 07:52
Thanks for the fix and new release!

**Comment by pjotrp** [comment] 2017-11-12 07:51
@rernst  would you mind signing up to the mailing list so we can discuss the future? https://groups.google.com/forum/#!forum/sambamba-discussion
