### ISSUE TITLE
subsampling gives unexpected number of reads

### ISSUE THREAD

**Issue by pkhoueiry** [lomereiter/sambamba#176] opened 2015-10-20 15:11 UTC
For each run of subsampling on the same input bam file (without subsampling seed option), the number of reads sampled for the same fraction chosen differs. Don't we expect when we subsample 5% of reads to get exactly 5% (and not 4.9 or 5.1), of course different 5% for different runs when no seed is chosen.

**Comment by lomereiter** [comment] 2015-10-20 17:27
Current approach is probabilistic, i.e. each read/read pair has 5% chance of being selected. This allows to use subsampling with pipes, without knowing the total number of reads.
I'm closing this as a duplicate of https://github.com/lomereiter/sambamba/issues/160.

**Closed by lomereiter** 2015-10-20 17:27 UTC
