### ISSUE TITLE
zero cov output problem

### ISSUE THREAD

**Issue by parlar** [lomereiter/sambamba#175] opened 2015-10-19 23:16 UTC
Hi again,

sambamba_v0.5.9 depth base -L bed -z (or --report-zero-coverage) bam 
does not seem to output zero-coverage bases?

cheers

Pär

**Comment by parlar** [comment] 2015-11-09 07:41
Sorry for bumping this issue. I guess that you have your hands full - as everyone. I'm just wondering if you were planning to look at this or if if you feel that it has a lower priority. Then I'll invest the time to make a work-around.

**Comment by lomereiter** [comment] 2015-11-09 08:39
Hi Pär, your guess is correct, but I look forward to making `depth` tool production-ready. A test case from your side would be very helpful.

**Comment by parlar** [comment] 2015-11-09 08:42
Sure! Just let me know. A bam file, targets.bed, and a reference depth call output using bedtools and the same input - would that be ok?

**Comment by lomereiter** [comment] 2015-11-09 08:43
Yes, that would be perfect.

**Comment by parlar** [comment] 2015-11-09 08:44
I'll make it available then and send you a link.

**Comment by lomereiter** [comment] 2016-06-19 15:09
closing as duplicate of #225

**Closed by lomereiter** 2016-06-19 15:09 UTC
Labels: depth base
