### ISSUE TITLE
stdout support on sort

### ISSUE THREAD

**Issue by pfxuan** [lomereiter/sambamba#171] opened 2015-10-12 14:38 UTC
Is it possible to add stdout support on `sambamba sort`? Something like the sort program in Samtools (`samtools sort -O bam -T ./tmp - `). This is a critical feature for building high performance pipeline. I got the following error when using stdout on `sambamba sort`
```bash
sambamba sort -t 1 -m 1G --tmpdir=./tmp -o /dev/stdout /dev/stdin
sambamba-sort: Cannot open or create file '/dev/stdout'
```

**Comment by lomereiter** [comment] 2015-10-12 17:50
Hi, I believe you are using Mac, so this is a duplicate of https://github.com/lomereiter/sambamba/issues/129?

**Comment by pfxuan** [comment] 2015-10-12 21:25
@lomereiter Yes, I actually saw #129 before submitting this ticket. But it looks like that issue have been stuck for a while. Is there any plan to add this feature? Thanks!

**Comment by lomereiter** [comment] 2015-10-13 07:06
Ok, I finally tested this, and indeed on Mac OS X /dev/stdout isn't writable for some reason. I've just pushed a commit which handles `-` output in `sort`: https://github.com/lomereiter/sambamba/commit/1a8037d768b4faaaf44fb69c999b9218cceaa194 (another news is that 'all' target now works on mac with dmd).

**Closed by lomereiter** 2015-10-13 07:06 UTC

**Comment by pfxuan** [comment] 2015-10-13 14:50
@lomereiter Thank you for your super fast response and patch! I had a hard time to get sambamba compiled on my MBP (Mac OS X is version 10.11, LDC is 0.15.2-beta2). Any thoughts on this? 
```bash
mkdir -p build/
ldmd2 @sambamba-ldmd-release.rsp
/usr/local/Cellar/ldc/0.15.2-beta2/include/d/std/numeric.d(1380): Deprecation: Read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"+="(s, e) instead.
/usr/local/Cellar/ldc/0.15.2-beta2/include/d/std/numeric.d(1405): Deprecation: Read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"*="(e, f) instead.
gcc -L/usr/local/Cellar/ldc/0.15.2-beta2/lib -dead_strip -lphobos2-ldc -ldruntime-ldc -lm -lpthread htslib/libhts.a lz4/lib/liblz4.a build/sambamba.o -o build/sambamba
ld: warning: object file (build/sambamba.o) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_char.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_ubyte.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_double.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_real.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_float.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_byte.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_int.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_uint.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_long.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_ulong.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_ushort.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_void.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_dchar.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_Ag.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_Afloat.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_Aint.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_Along.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(object_.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(functional.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(parallelism.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(regex.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(uni.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(utf.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(conv.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(file.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(json.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(math.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(path.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(array.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(process.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(ascii.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(range.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(stdio.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(format.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(getopt.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(random.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(stream.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(string.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(traits.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(cstream.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(numeric.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(bitmanip.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(datetime.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(unicode_tables.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(typecons.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(algorithm.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(package.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(exception.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(select.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(errno.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(mutex.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(condition.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(time.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(bitop.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(memory.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(thread.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(sections_ldc.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(aApplyR.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(aApply.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(aaA.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(adi.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(lifetime.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(arrayinit.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(critical_.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(eh.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(cast_.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(dmain2.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(switch_.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_creal.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_ireal.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_ifloat.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_idouble.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_cfloat.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_cdouble.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_short.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_wchar.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(ti_Ashort.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(utf.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(hash.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(string.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(common.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(minfo.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(tlsgc.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(memory.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(crc.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(mmfile.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(complex.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(processinit.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(unicode_comp.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(binaryheap.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(array.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(dlist.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(slist.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(rbtree.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(stdiobase.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(stat.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(wait.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(config.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(exception.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(cpuid.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(exception.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(monitor_.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(qsort.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(proxy.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(runtime.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(gc.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(digest.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libphobos2-ldc.a(util.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(demangle.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(os.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(bits.o)) was built for newer OSX version (15.0) than being linked (10.11)
ld: warning: object file (/usr/local/Cellar/ldc/0.15.2-beta2/lib/libdruntime-ldc.a(random.o)) was built for newer OSX version (15.0) than being linked (10.11)
Undefined symbols for architecture x86_64:
  "__D8sambamba5utils6common4file12__ModuleInfoZ", referenced from:
      __D8sambamba4sort12__ModuleInfoZ in sambamba.o
  "__D8sambamba5utils6common4file12bufferedFileFAyaE3std6stream8FileModemZC3std6stream12BufferedFile", referenced from:
      __D8sambamba4sort6Sorter4dumpMFAS3bio3bam4read7BamReadZv in sambamba.o
      __D8sambamba4sort6Sorter57__T17mergeSortedChunksS313bio3bam4read16compareReadNamesZ17mergeSortedChunksMFZv in sambamba.o
      __D8sambamba4sort6Sorter62__T17mergeSortedChunksS363bio3bam4read21mixedCompareReadNamesZ17mergeSortedChunksMFZv in sambamba.o
      __D8sambamba4sort6Sorter59__T17mergeSortedChunksS333bio3bam4read18compareCoordinatesZ17mergeSortedChunksMFZv in sambamba.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sambamba-ldmd2-64] Error 1
```

**Comment by lomereiter** [comment] 2015-10-13 16:26
Sorry about that, please pull the latest commit.

**Comment by pfxuan** [comment] 2015-10-13 16:32
@lomereiter it works like a charm! I'll let you know if I have further issue on using `sambamba sort`. Thank you for all your hard work!
