### ISSUE TITLE
Trying to install sambamba on 32-bit ubuntu 

### ISSUE THREAD

**Issue by kb472** [lomereiter/sambamba#195] opened 2016-03-14 20:56 UTC
Trying to install Sambamba on my ubuntu machine. 

Tried both types of installation shown below, but can't get this to work. Could some one tell me how they got it to work on an Ubuntu machine (I am quite a newbie)

```
wget https://github.com/lomereiter/sambamba/releases/download/v0.5.2/sambamba_v0.5.2_linux.tar.bz2
tar -xjvf sambamba_v0.5.2_linux.tar.bz2
chmod +x sambamba*
sudo mv sambamba* /usr/bin/sambamba
```

```
 git clone --recursive https://github.com/lomereiter/sambamba.git
 cd sambamba
 make sambamba-ldmd2-64
```

Thank you

**Comment by lomereiter** [comment] 2016-03-14 21:30
Hi, the mistake you're making is that `sambamba*` gets expanded into the name of extracted executable and the name of the archive, and you want only the former. Just specify the executable explicitly. I also recommend to either use `/usr/local/bin` or just append containing directory to the `PATH`, because `/usr/bin/` is supposed to be used only for software installed through package manager. And please use the latest version unless you have a specific reason not to (e.g. a regression).

**Comment by kb472** [comment] 2016-03-14 21:50
Thank you for the feedback. So I tried  this:
```
wget https://github.com/lomereiter/sambamba/releases/download/v0.5.2/sambamba_v0.5.2_linux.tar.bz2
tar -xjvf sambamba_v0.5.2_linux.tar.bz2
rm sambamba*.tar.bz2
chmod +x sambamba*
# create directory sambamba in /usr/local/bin
sudo mv sambamba* /usr/local/bin/sambamba
```
So now there is an executable file "sambamba_v0.5.2" in my /usr/local/bin/sambamba

So when I type "sambamba" on the command prompt for testing, it still says "sambamba: command not found". What am I doing wrong ?

**Comment by lomereiter** [comment] 2016-03-15 07:43
You should rename the executable to `sambamba`, bash shell won't do any magic for you, it just goes through the paths listed in `PATH` variable until it finds the requested filename.

**Comment by kb472** [comment] 2016-03-16 03:56
Yes, I tried that. Still gives me this error: cannot execute binary file: Exec format error.

**Comment by biocyberman** [comment] 2016-03-16 19:12
Follow these steps, you are almost there. 
```
~ ➤ wget wget https://github.com/lomereiter/sambamba/releases/download/v0.5.2/sambamba_v0.5.2_linux.tar.bz2            
2016-03-16 19:16:07 (921 KB/s) - ‘sambamba_v0.5.2_linux.tar.bz2’ saved [1372085/1372085]

FINISHED --2016-03-16 19:16:07--
Total wall clock time: 4.1s
Downloaded: 1 files, 1.3M in 1.5s (921 KB/s)
~ ➤ tar xjf sambamba_v0.5.2_linux.tar.bz2                                                                              
~ ➤ ls -lah sambamba_v0.5.2                                                                                            
-rw-r--r-- 1 user user 5.7M Apr  7  2015 sambamba_v0.5.2
~ ➤ chmod +x sambamba_v0.5.2 
# make a test run before moving.                                                                                          
~ ➤ ./sambamba_v0.5.2                                                                                                  
sambamba v0.5.2

Usage: sambamba [command] [args...]

    Available commands: 'view', 'index', 'merge', 'sort',
                        'flagstat', 'slice', 'markdup', 'depth', 'mpileup'
    To get help on a particular command, just call it without args.

Leave bug reports and feature requests at
https://github.com/lomereiter/sambamba/issues
# Clean up, check carefully the following command before hitting enter.
sudo rm -rf /usr/local/bin/sambamba* 
# Now do the moving
sudo cp sambamba_v0.5.2 /usr/local/bin/sambamba
# Now test again
~ ➤ sambamba                                                              
sambamba v0.5.2

Usage: sambamba [command] [args...]

    Available commands: 'view', 'index', 'merge', 'sort',
                        'flagstat', 'slice', 'markdup', 'depth', 'mpileup'
    To get help on a particular command, just call it without args.

Leave bug reports and feature requests at
https://github.com/lomereiter/sambamba/issues
# Done
```

**Comment by lomereiter** [comment] 2016-03-16 20:20
@kb472: "Exec format error" suggests that you're using 32-bit operating system. In general, bioinformaticians prefer 64-bit systems because many computational problems are easier solved with lots of memory (which is cheap nowadays), so I don't even make 32-bit releases.

That said, I've just pushed a few changes to fix compilation on 32-bit, but you'll have to compile it yourself. Here's how:
```bash
# install build dependencies
apt-get update
apt-get install -y --no-install-recommends gcc make wget xz-utils git

# install LDC compiler
wget https://github.com/ldc-developers/ldc/releases/download/v0.17.0/ldc2-0.17.0-linux-x86.tar.xz
tar xJf ldc2-0.17.0-linux-x86.tar.xz
export PATH=`pwd`/ldc2-0.17.0-linux-x86/bin:$PATH
export LIBRARY_PATH=`pwd`/ldc2-0.17.0-linux-x86/lib # needed for linking

# build the tool (the executable will be in build/ subdirectory)
git clone --recursive https://github.com/lomereiter/sambamba
cd sambamba && sed -i 's/m64/m32/' sambamba-ldmd-release.rsp
make sambamba-ldmd2-64
```

**Comment by lomereiter** [comment] 2016-07-16 05:14
Closing until there's more interest in 32-bit.

**Closed by lomereiter** 2016-07-16 05:14 UTC
Labels: wontfix
