### ISSUE TITLE
sambamba mpileup stop working

### ISSUE THREAD

**Issue by danro9685** [lomereiter/sambamba#249] opened 2016-09-27 17:04 UTC
Hi, 

I have been trying to run the following command /usr/local/sambamba_v0.6.4 mpileup -o /usr/local/normal.mpileup /usr/local/normal_sample.bam --samtools -f /usr/local/reference_genome.fa with samtools-1.3.1 on Ubuntu 12.04. 

Everything seems to work fine up to a certain point when the program keeps running without doing anything. 

Any reason this may be happening? 

Thanks, 
Daniele

**Comment by lomereiter** [comment] 2016-09-28 07:35
Hi, that sounds like a duplicate of #242 (and suggests it's time for a new release).
I'll take time to look at https://github.com/lomereiter/sambamba/pull/247 more thoroughly, it could be something is still overlooked there.

**Comment by pjotrp** [comment] 2017-02-23 17:46
Due to inactivity.

**Closed by pjotrp** 2017-02-23 17:46 UTC
