### ISSUE TITLE
sambamba sort error

### ISSUE THREAD

**Issue by avilella** [lomereiter/sambamba#202] opened 2016-04-01 15:37 UTC
I got this error when running sambamba:

```
++ sambamba sort -t 16 C89BBANXX_102775-001-001_ATCACGAT_L006_R1_cut2.ernemethyl.bam
sambamba-sort: Bin in read with name 'D00476:214:C89BBANXX:6:2206:18364:98254' is set incorrectly (5627 instead of expected 703)Apr 1, 2016 4:16 PM
Close
```
Any ideas?

**Comment by lomereiter** [comment] 2016-04-01 16:35
Looks like a duplicate of https://github.com/lomereiter/sambamba/issues/163 which was fixed. Which version are you using?

**Comment by avilella** [comment] 2016-04-02 14:34
Should this be fixed in 0.5.9? There is a linux bin (I want it for Ubuntu) for 0.5.9 but not for 0.6.0

**Comment by lomereiter** [comment] 2016-04-02 18:10
It should be. There actually is a linux bin for 0.6.0, I just inadvertently used some prehistoric naming (renamed it now).

**Comment by avilella** [comment] 2016-04-04 08:04
Thanks you. Indeed 0.6.0 works on the Ubuntu instance I was using and it
resolves this issue. Can close ticket.

**Closed** 2016-04-04 08:17 UTC
