### ISSUE TITLE
bam index pseudo bin (bin 37450) for unmapped_beg is extended to the end of file

### ISSUE THREAD

**Issue by liuxf09** [lomereiter/sambamba#287] opened 2017-03-17 23:11 UTC
According to sam/bam spec v1 at page 14, pseudo bin unmapped_beg should be "file offset of the start of placed unmapped reads ". But bam index generated by sambamba for that field is extended to the end of file (end of file minus 28 for exact). This is clearly a violation of sam/bam spec. Maybe there is a reason to change to the current value?

**Comment by lomereiter** [comment] 2017-03-18 06:28
Closing as duplicate of #210

**Closed by lomereiter** 2017-03-18 06:28 UTC
